// Demo data for the prototype - simulates Firebase data

const DEMO_MANUFACTURERS = [
  {
    id: "mfr-001",
    companyName: "Sri Lakshmi Textiles",
    ownerName: "Rajesh Kumar",
    email: "rajesh@srilakshmi.com",
    phone: "+91-422-2345678",
    location: "Coimbatore, Tamil Nadu",
    gstNumber: "33AABCS1234A1Z5",
    specialization: "Cotton & Silk Fabrics",
    established: 1995,
    verified: true,
    rating: 4.8,
    totalProducts: 24,
    avatar: null,
  },
  {
    id: "mfr-002",
    companyName: "Surat Silk House",
    ownerName: "Amit Patel",
    email: "amit@suratsilk.com",
    phone: "+91-261-2456789",
    location: "Surat, Gujarat",
    gstNumber: "24AABCS5678B2Z3",
    specialization: "Silk & Synthetic Blends",
    established: 2003,
    verified: true,
    rating: 4.5,
    totalProducts: 18,
    avatar: null,
  },
  {
    id: "mfr-003",
    companyName: "Tirupur Knits Pvt Ltd",
    ownerName: "Saravanan M",
    email: "saravanan@tirupurknits.com",
    phone: "+91-421-2567890",
    location: "Tirupur, Tamil Nadu",
    gstNumber: "33AABCT9012C3Z1",
    specialization: "Knitted Cotton Garments",
    established: 2010,
    verified: true,
    rating: 4.6,
    totalProducts: 32,
    avatar: null,
  },
  {
    id: "mfr-004",
    companyName: "Bhagalpur Silk Weavers Co-op",
    ownerName: "Priya Devi",
    email: "priya@bhagalpursilk.com",
    phone: "+91-641-2678901",
    location: "Bhagalpur, Bihar",
    gstNumber: "10AABCB3456D4Z7",
    specialization: "Tussar Silk & Handlooms",
    established: 1988,
    verified: true,
    rating: 4.9,
    totalProducts: 15,
    avatar: null,
  },
  {
    id: "mfr-005",
    companyName: "Varanasi Brocade House",
    ownerName: "Mohammed Ansari",
    email: "ansari@varanasibrocade.com",
    phone: "+91-542-2789012",
    location: "Varanasi, Uttar Pradesh",
    gstNumber: "09AABCV7890E5Z9",
    specialization: "Banarasi Silk & Brocade",
    established: 1972,
    verified: true,
    rating: 4.7,
    totalProducts: 21,
    avatar: null,
  },
];

const DEMO_PRODUCTS = [
  {
    id: "prod-001",
    manufacturerId: "mfr-001",
    fabricId: "FID-A3B7C9D2",
    productName: "Premium Cotton Saree - Temple Border",
    description: "Handwoven cotton saree with traditional temple border design. Soft texture with excellent drape.",
    images: ["/demo/cotton-saree-1.jpg", "/demo/cotton-saree-2.jpg", "/demo/cotton-saree-3.jpg"],
    analysis: {
      weavePattern: "Plain Weave",
      fabricType: "Cotton",
      textureProfile: "Smooth & Fine",
      colorProfile: { dominant: "#D4A574", secondary: "#8B4513", accent: "#F5DEB3", name: "Natural Earth Tones" },
      threadCount: 120,
      gsmWeight: 180,
      qualityScore: 92,
      fiberComposition: [{ fiber: "Cotton", percentage: 100 }],
      durabilityRating: 4,
      colorfastness: 5,
    },
    fingerprint: "A3B7-C9D2-E1F4-8765",
    price: "2,500",
    currency: "INR",
    category: "Sarees",
    createdAt: "2024-01-15T10:30:00Z",
    status: "verified",
    scanCount: 145,
  },
  {
    id: "prod-002",
    manufacturerId: "mfr-001",
    fabricId: "FID-F4E8D1C5",
    productName: "Silk Cotton Blend - Kanchipuram Style",
    description: "Premium silk-cotton blend with Kanchipuram-inspired motifs. Rich colors with golden zari work.",
    images: ["/demo/silk-cotton-1.jpg", "/demo/silk-cotton-2.jpg", "/demo/silk-cotton-3.jpg"],
    analysis: {
      weavePattern: "Jacquard",
      fabricType: "Silk",
      textureProfile: "Silky & Lustrous",
      colorProfile: { dominant: "#8E44AD", secondary: "#3498DB", accent: "#1ABC9C", name: "Royal Purple & Blue" },
      threadCount: 200,
      gsmWeight: 220,
      qualityScore: 96,
      fiberComposition: [{ fiber: "Silk", percentage: 60 }, { fiber: "Cotton", percentage: 40 }],
      durabilityRating: 5,
      colorfastness: 4,
    },
    fingerprint: "F4E8-D1C5-B2A9-3456",
    price: "8,500",
    currency: "INR",
    category: "Sarees",
    createdAt: "2024-02-20T14:15:00Z",
    status: "verified",
    scanCount: 89,
  },
  {
    id: "prod-003",
    manufacturerId: "mfr-002",
    fabricId: "FID-B2C6D8E3",
    productName: "Designer Silk Dupatta",
    description: "Lightweight silk dupatta with contemporary geometric patterns. Perfect for both casual and formal wear.",
    images: ["/demo/silk-dupatta-1.jpg", "/demo/silk-dupatta-2.jpg", "/demo/silk-dupatta-3.jpg"],
    analysis: {
      weavePattern: "Satin Weave",
      fabricType: "Silk",
      textureProfile: "Silky & Lustrous",
      colorProfile: { dominant: "#1ABC9C", secondary: "#3498DB", accent: "#E8DAEF", name: "Teal & Azure" },
      threadCount: 180,
      gsmWeight: 90,
      qualityScore: 88,
      fiberComposition: [{ fiber: "Silk", percentage: 95 }, { fiber: "Nylon", percentage: 5 }],
      durabilityRating: 3,
      colorfastness: 4,
    },
    fingerprint: "B2C6-D8E3-A4F1-7890",
    price: "3,200",
    currency: "INR",
    category: "Dupattas",
    createdAt: "2024-03-10T09:45:00Z",
    status: "verified",
    scanCount: 67,
  },
  {
    id: "prod-004",
    manufacturerId: "mfr-003",
    fabricId: "FID-E7A1B5C9",
    productName: "Organic Cotton T-Shirt Fabric",
    description: "GOTS certified organic cotton knit fabric. Ideal for premium T-shirt manufacturing. 160 GSM single jersey.",
    images: ["/demo/organic-cotton-1.jpg", "/demo/organic-cotton-2.jpg", "/demo/organic-cotton-3.jpg"],
    analysis: {
      weavePattern: "Plain Weave",
      fabricType: "Cotton",
      textureProfile: "Soft & Brushed",
      colorProfile: { dominant: "#27AE60", secondary: "#2ECC71", accent: "#F39C12", name: "Forest & Gold" },
      threadCount: 100,
      gsmWeight: 160,
      qualityScore: 94,
      fiberComposition: [{ fiber: "Cotton", percentage: 100 }],
      durabilityRating: 4,
      colorfastness: 5,
    },
    fingerprint: "E7A1-B5C9-D3F2-1234",
    price: "450/meter",
    currency: "INR",
    category: "Fabric Rolls",
    createdAt: "2024-04-05T11:20:00Z",
    status: "verified",
    scanCount: 234,
  },
  {
    id: "prod-005",
    manufacturerId: "mfr-004",
    fabricId: "FID-C8D2E6F1",
    productName: "Tussar Silk Stole - Natural Dye",
    description: "Hand-spun Tussar silk stole with natural vegetable dyes. Each piece is unique with slight color variations.",
    images: ["/demo/tussar-stole-1.jpg", "/demo/tussar-stole-2.jpg", "/demo/tussar-stole-3.jpg"],
    analysis: {
      weavePattern: "Twill Weave",
      fabricType: "Silk",
      textureProfile: "Medium Texture",
      colorProfile: { dominant: "#E67E22", secondary: "#D35400", accent: "#FDE3A7", name: "Warm Sunset" },
      threadCount: 150,
      gsmWeight: 130,
      qualityScore: 97,
      fiberComposition: [{ fiber: "Silk", percentage: 100 }],
      durabilityRating: 4,
      colorfastness: 3,
    },
    fingerprint: "C8D2-E6F1-A5B3-5678",
    price: "4,800",
    currency: "INR",
    category: "Stoles & Scarves",
    createdAt: "2024-05-12T16:30:00Z",
    status: "verified",
    scanCount: 56,
  },
];

export { DEMO_MANUFACTURERS, DEMO_PRODUCTS };
